#!/bin/sh
set -e

# Docker script to configure and start an Http Proxy Server
# This script is intended to run inside the container only.

conf_dir="/etc/squid"
auto_conf="${conf_dir}/auto.conf"

load_env_defaults() {
    file_path="$1"
    if [ ! -f "${file_path}" ]; then
        return 0
    fi

    while IFS= read -r line || [ -n "${line}" ]; do
        case "${line}" in
            ''|\#*)
                continue
                ;;
        esac

        key="${line%%=*}"
        val="${line#*=}"
        key="$(echo "${key}" | tr -d '[:space:]')"

        case "${key}" in
            ''|*[!A-Za-z0-9_]*)
                continue
                ;;
        esac

        eval "is_set=\${${key}+x}"
        if [ -z "${is_set}" ]; then
            eval "export ${key}=\"\${val}\""
        fi
    done < "${file_path}"
}

# Load runtime overrides first, then image defaults.
load_env_defaults "/etc/squid/.env"
load_env_defaults "/opt/src/.env"

# Tunables (can be overridden by environment variables)
CONFIG_CHECK_INTERVAL_SECONDS="${CONFIG_CHECK_INTERVAL_SECONDS:-30}"
LOG_ROTATE_INTERVAL_SECONDS="${LOG_ROTATE_INTERVAL_SECONDS:-86400}"
LOG_ROTATE_MAX_SIZE_MB="${LOG_ROTATE_MAX_SIZE_MB:-100}"
LOGFILE_ROTATE="${LOGFILE_ROTATE:-10}"

CACHE_MEM_RATIO_PCT="${CACHE_MEM_RATIO_PCT:-10}"
CACHE_MEM_MIN_MB="${CACHE_MEM_MIN_MB:-64}"
CACHE_MEM_MAX_MB="${CACHE_MEM_MAX_MB:-2048}"

CACHE_DIR_RATIO_PCT="${CACHE_DIR_RATIO_PCT:-50}"
CACHE_DIR_MIN_MB="${CACHE_DIR_MIN_MB:-256}"
CACHE_DIR_LEVEL1="${CACHE_DIR_LEVEL1:-16}"
CACHE_DIR_LEVEL2="${CACHE_DIR_LEVEL2:-256}"

clamp() {
    _value="$1"
    _min="$2"
    _max="$3"
    if [ "${_value}" -lt "${_min}" ]; then
        echo "${_min}"
    elif [ "${_value}" -gt "${_max}" ]; then
        echo "${_max}"
    else
        echo "${_value}"
    fi
}

generate_runtime_config() {
    mem_total_kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
    if [ -z "${mem_total_kb}" ] || [ "${mem_total_kb}" -le 0 ]; then
        mem_total_kb=524288
    fi
    mem_total_mb=$((mem_total_kb / 1024))
    cache_mem_mb=$((mem_total_mb * CACHE_MEM_RATIO_PCT / 100))
    cache_mem_mb="$(clamp "${cache_mem_mb}" "${CACHE_MEM_MIN_MB}" "${CACHE_MEM_MAX_MB}")"

    cache_fs_free_mb="$(df -Pm /var/cache/squid 2>/dev/null | awk 'NR==2 {print $4}' || echo 0)"
    if [ -z "${cache_fs_free_mb}" ] || [ "${cache_fs_free_mb}" -le 0 ]; then
        cache_fs_free_mb=1024
    fi
    cache_dir_mb=$((cache_fs_free_mb * CACHE_DIR_RATIO_PCT / 100))
    if [ "${cache_fs_free_mb}" -gt 256 ]; then
        cache_dir_max_mb=$((cache_fs_free_mb - 128))
    else
        cache_dir_max_mb=$((cache_fs_free_mb * 80 / 100))
    fi
    if [ "${cache_dir_max_mb}" -lt 64 ]; then
        cache_dir_max_mb=64
    fi
    cache_dir_min_effective="${CACHE_DIR_MIN_MB}"
    if [ "${cache_dir_min_effective}" -gt "${cache_dir_max_mb}" ]; then
        cache_dir_min_effective="${cache_dir_max_mb}"
    fi
    cache_dir_mb="$(clamp "${cache_dir_mb}" "${cache_dir_min_effective}" "${cache_dir_max_mb}")"

    cat > "${auto_conf}" <<EOF
# Generated by run.sh at container startup.
cache_mem ${cache_mem_mb} MB
cache_dir ufs /var/cache/squid ${cache_dir_mb} ${CACHE_DIR_LEVEL1} ${CACHE_DIR_LEVEL2}
logfile_rotate ${LOGFILE_ROTATE}
EOF

    echo "Generated ${auto_conf}: cache_mem=${cache_mem_mb}MB cache_dir=${cache_dir_mb}MB logfile_rotate=${LOGFILE_ROTATE}"
}

# Ensure cache and log dirs exist with sensible permissions
mkdir -p /var/cache/squid /var/log/squid
chown -R squid:squid /var/cache/squid /var/log/squid || true
mkdir -p "${conf_dir}"

generate_runtime_config

# Initialize Squid cache directory if needed (safe to run on every start)
echo "Initializing squid cache directory (squid -z)..."
set +e
squid -z
_rc=$?
set -e
if [ $_rc -ne 0 ]; then
    echo "Warning: squid -z returned non-zero ($_rc). Continuing startup."
fi

# Start squid in foreground mode so container exits if squid exits.
squid -N &
SQUID_PID=$!

# Compute initial checksum of config directory (if present)
previous_status="$(find "${conf_dir}" -type f -exec md5sum {} \; | sort -k 2 | md5sum 2>/dev/null || true)"
next_rotate_epoch="$(( $(date +%s) + LOG_ROTATE_INTERVAL_SECONDS ))"

stop() {
    echo "Stopping container, shutting down squid..."
    squid -k shutdown || true
}

trap 'stop; exit 0' TERM INT

while kill -0 "${SQUID_PID}" 2>/dev/null; do
    sleep "${CONFIG_CHECK_INTERVAL_SECONDS}"
    current_status="$(find "${conf_dir}" -type f -exec md5sum {} \; | sort -k 2 | md5sum 2>/dev/null || true)"
    if [ "${previous_status}" = "${current_status}" ]; then
        echo "No config changes detected..."
    else
        echo "Changes found in settings, reloading squid configuration..."
        squid -k reconfigure || echo "squid reconfigure failed"
        previous_status="${current_status}"
    fi

    now_epoch="$(date +%s)"
    access_log_size_mb="$(du -m /var/log/squid/access.log 2>/dev/null | awk '{print $1}' || echo 0)"
    cache_log_size_mb="$(du -m /var/log/squid/cache.log 2>/dev/null | awk '{print $1}' || echo 0)"
    if [ -z "${access_log_size_mb}" ]; then access_log_size_mb=0; fi
    if [ -z "${cache_log_size_mb}" ]; then cache_log_size_mb=0; fi

    if [ "${now_epoch}" -ge "${next_rotate_epoch}" ] || \
       [ "${access_log_size_mb}" -ge "${LOG_ROTATE_MAX_SIZE_MB}" ] || \
       [ "${cache_log_size_mb}" -ge "${LOG_ROTATE_MAX_SIZE_MB}" ]; then
        echo "Rotating logs (access=${access_log_size_mb}MB cache=${cache_log_size_mb}MB)..."
        squid -k rotate || echo "squid log rotate failed"
        next_rotate_epoch="$((now_epoch + LOG_ROTATE_INTERVAL_SECONDS))"
    fi
done

wait "${SQUID_PID}"
